/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package olympia;

import static olympia.Client.din;
import static olympia.Client.dout;
import static olympia.Client.s;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author H
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
    }

    public JTextArea getMsgArea() {
        return msgArea;
    }

    public void setMsgArea(JTextArea msgArea) {
        this.msgArea = msgArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgLeave = new javax.swing.JButton();
        msgStart = new javax.swing.JButton();
        msgRoomName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        msgPlayer1 = new javax.swing.JLabel();
        msgPlayer2 = new javax.swing.JLabel();
        msgPlayer3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        msgArea = new javax.swing.JTextArea();
        msgText = new javax.swing.JTextField();
        msgSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msgLeave.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        msgLeave.setText("Leave");
        msgLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgLeaveActionPerformed(evt);
            }
        });

        msgStart.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        msgStart.setText("Start");
        msgStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgStartActionPerformed(evt);
            }
        });

        msgRoomName.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        msgRoomName.setText("Room1");

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("Player :");

        msgPlayer1.setFont(new java.awt.Font("Segoe Print", 1, 20)); // NOI18N
        msgPlayer1.setText("Phuong");

        msgPlayer2.setFont(new java.awt.Font("Segoe Print", 1, 20)); // NOI18N
        msgPlayer2.setText("Tung");

        msgPlayer3.setFont(new java.awt.Font("Segoe Print", 1, 20)); // NOI18N
        msgPlayer3.setText("Hieu");

        msgArea.setColumns(20);
        msgArea.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        msgArea.setRows(5);
        jScrollPane2.setViewportView(msgArea);

        msgText.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        msgText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgTextActionPerformed(evt);
            }
        });

        msgSend.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        msgSend.setText("Send");
        msgSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83)
                        .addComponent(msgPlayer1)
                        .addGap(84, 84, 84)
                        .addComponent(msgPlayer2)
                        .addGap(85, 85, 85)
                        .addComponent(msgPlayer3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(msgLeave)
                        .addGap(119, 119, 119)
                        .addComponent(msgStart))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(msgText, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(msgSend)))))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(msgRoomName)
                .addGap(310, 310, 310))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(msgRoomName)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msgPlayer1)
                    .addComponent(jLabel1)
                    .addComponent(msgPlayer2)
                    .addComponent(msgPlayer3))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msgText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msgSend))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msgLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msgStart, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msgLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgLeaveActionPerformed
        try {
            String msgout = "leave";
            dout.writeUTF(msgout);
        } catch (IOException ex) {
            Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_msgLeaveActionPerformed

    private void msgStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgStartActionPerformed
        try {
            String msgout = "start";
            dout.writeUTF(msgout);
        } catch (IOException ex) {
            Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_msgStartActionPerformed

    private void msgTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msgTextActionPerformed

    private void msgSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgSendActionPerformed
        try {
            String msgout = "(send)";
            msgout = msgout.concat(msgText.getText().trim());
            dout.writeUTF(msgout);
        } catch (IOException ex) {
            Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_msgSendActionPerformed

    public JLabel getMsgPlayer1() {
        return msgPlayer1;
    }

    public void setMsgPlayer1(JLabel msgPlayer1) {
        this.msgPlayer1 = msgPlayer1;
    }

    public JLabel getMsgPlayer2() {
        return msgPlayer2;
    }

    public void setMsgPlayer2(JLabel msgPlayer2) {
        this.msgPlayer2 = msgPlayer2;
    }

    public JLabel getMsgPlayer3() {
        return msgPlayer3;
    }

    public void setMsgPlayer3(JLabel msgPlayer3) {
        this.msgPlayer3 = msgPlayer3;
    }

    public JLabel getMsgRoomName() {
        return msgRoomName;
    }

    public void setMsgRoomName(JLabel msgRoomName) {
        this.msgRoomName = msgRoomName;
    }

    public JButton getMsgSend() {
        return msgSend;
    }

    public void setMsgSend(JButton msgSend) {
        this.msgSend = msgSend;
    }

    public JTextField getMsgText() {
        return msgText;
    }

    public void setMsgText(JTextField msgText) {
        this.msgText = msgText;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea msgArea;
    private javax.swing.JButton msgLeave;
    private javax.swing.JLabel msgPlayer1;
    private javax.swing.JLabel msgPlayer2;
    private javax.swing.JLabel msgPlayer3;
    private javax.swing.JLabel msgRoomName;
    private javax.swing.JButton msgSend;
    private javax.swing.JButton msgStart;
    private javax.swing.JTextField msgText;
    // End of variables declaration//GEN-END:variables
}
