/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package olympia;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import static olympia.Client.dout;

/**
 *
 * @author H
 */
public class Gamefinish extends javax.swing.JFrame {

    /**
     * Creates new form Gamefinish
     */
    public Gamefinish() {
        initComponents();
    }

    public JLabel getMsgName1() {
        return msgName1;
    }

    public void setMsgName1(JLabel msgName1) {
        this.msgName1 = msgName1;
    }

    public JLabel getMsgName2() {
        return msgName2;
    }

    public void setMsgName2(JLabel msgName2) {
        this.msgName2 = msgName2;
    }

    public JLabel getMsgName3() {
        return msgName3;
    }

    public void setMsgName3(JLabel msgName3) {
        this.msgName3 = msgName3;
    }

    public JLabel getMsgScore1() {
        return msgScore1;
    }

    public void setMsgScore1(JLabel msgScore1) {
        this.msgScore1 = msgScore1;
    }

    public JLabel getMsgScore2() {
        return msgScore2;
    }

    public void setMsgScore2(JLabel msgScore2) {
        this.msgScore2 = msgScore2;
    }

    public JLabel getMsgScore3() {
        return msgScore3;
    }

    public void setMsgScore3(JLabel msgScore3) {
        this.msgScore3 = msgScore3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgContinue = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        msgScore3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        msgName1 = new javax.swing.JLabel();
        msgName2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        msgName3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        msgScore1 = new javax.swing.JLabel();
        msgScore2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msgContinue.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        msgContinue.setText("Continue");
        msgContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgContinueActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("1");

        msgScore3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setText("3");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setText("Rank");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel5.setText("2");

        msgName1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N

        msgName2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel8.setText("Name");

        msgName3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel10.setText("Score");

        msgScore1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N

        msgScore2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel13.setText("Leaderboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(20, 20, 20)))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(msgName3)
                            .addComponent(msgName1)
                            .addComponent(msgName2))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msgScore3)
                            .addComponent(jLabel10)
                            .addComponent(msgScore1)
                            .addComponent(msgScore2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(msgContinue)))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel13)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(msgName1)
                    .addComponent(msgScore1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msgName2)
                    .addComponent(jLabel5)
                    .addComponent(msgScore2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msgName3)
                    .addComponent(msgScore3)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addComponent(msgContinue)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msgContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgContinueActionPerformed
        try {
            String msgout = "(continue)";
            dout.writeUTF(msgout);
        } catch (IOException ex) {
            Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_msgContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gamefinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gamefinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gamefinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gamefinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gamefinish().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton msgContinue;
    private javax.swing.JLabel msgName1;
    private javax.swing.JLabel msgName2;
    private javax.swing.JLabel msgName3;
    private javax.swing.JLabel msgScore1;
    private javax.swing.JLabel msgScore2;
    private javax.swing.JLabel msgScore3;
    // End of variables declaration//GEN-END:variables
}
